### ISSUE TITLE
Create seperated config files.

### ISSUE THREAD

**Issue by mfozmen** [BrewInteractive/authentication-service-nestjs#73]
https://docs.nestjs.com/techniques/configuration#custom-configuration-files

**Comment by ismetkizgin** [comment]
We are actively using it in the project

**Comment by mfozmen** [comment]
I mean we can use this:

<img width="880" alt="image" src="https://github.com/BrewInteractive/authentication-service-nestjs/assets/39158545/2a337775-ba0d-4257-a6bd-7237fad8632b">
